# This is a basic workflow to help you get started with Actions
name: Build and Distribute

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs:
#   pass-secret-to-action:
#     runs-on: ubuntu-latest

#     steps:  
#       - name: Pass the received secret to an action
#         uses: ./.github/actions/my-action@v1
#         with:
#           token: ${{ secrets.access-token }}          

# A workflow run is comprised of at least one job.
jobs:
  build:
    # The sort of virtual host machine to run the activity on. For our case, we need ubuntu-latest.
    # Each ubuntu host machine contains different installed software. You can check a list of supported software, tools, and packages in each virtual environment here: https://help.github.com/en/github/automating-your-workflow-with-github-actions/software-in-virtual-environments-for-github-actions
    runs-on: ubuntu-latest

    # Set up the Flutter environment for Github Actions.
    steps:
    - uses: actions/checkout@v2

    # Note: This workflow uses the latest stable version of the Flutter SDK.
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    # Get flutter dependencies.
    - run: flutter pub get
      
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
      
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
      
    # Run widget tests for our flutter project.
    #- run: flutter test
      
    # Build apk.
    - run: flutter build apk
      
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@master
      with:
        name: apk-release
        path: build/app/outputs/bundle/release

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_FACESHOT_TEACHER_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/app/outputs/apk/release/app-release.apk